// Generated by CoffeeScript 1.7.1
var JSON, MongoClient, Server, app, express, http, path, spidey, spideyUdp, spidey_UDP_IP, spidey_UDP_port;

http = require('http');

express = require('express');

MongoClient = require('mongodb').MongoClient;

Server = require('mongodb').Server;

path = require('path');

JSON = require('JSON');

spideyUdp = require('./spideyUdp');

spidey_UDP_IP = "192.168.0.227";

spidey_UDP_port = 7;

console.log(spideyUdp);

spidey = new spideyUdp.SpideyUDP(spidey_UDP_IP, spidey_UDP_port);

app = express();

app.set('port', process.env.PORT || 5078);

app.set('views', path.join(__dirname, 'views'));

app.set('view engine', 'jade');

app.all('*', function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*");
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  return next();
});

app.use(express["static"](__dirname + '/'));

app.get('/scripts/all.json', function(req, res) {
  return res.send("{\n	\"scripts\": \n	[\n		{\n		 	\"name\": \"Snake\", \n			\"desc\": \"A snake program\",\n			\"code\": \"var x = 10; function snake()\"\n		},\n		{\n		 	\"name\": \"Snake2\", \n			\"desc\": \"Another snake program\",\n			\"code\": \"var x = 10; function snake() { console.log ('hello'); }\"\n		}				\n	]\n}");
});

app.get('/rawcmd/:spideycommand', function(req, res) {
  var spideycommand;
  spideycommand = req.params.spideycommand;
  spidey.execCmd(spideycommand);
  return res.send("ok");
});

app.use(function(req, res) {
  return res.render('404', {
    url: req.url
  });
});

http.createServer(app).listen(app.get('port'), function() {
  return console.log('Spidey server listening on port ' + app.get('port'));
});
