// Generated by CoffeeScript 1.7.1
var getSnippets, selectScript;

getSnippets = function() {
  var jqXHR;
  jqXHR = $.getJSON("scripts/all.json", function(data) {
    var items;
    items = [];
    window.spideyScripts = data;
    $.each(data.scripts, function(idx, script) {
      items.push("<div class=\"post-frame\">\n	<a onclick=\"selectScript(" + idx + ")\" class=\"button\" id=\"" + idx + "\">" + script.name + "</a>\n</div>");
    });
    $("<ul/>", {
      "class": "my-new-list",
      html: items.join("")
    }).appendTo(".scripts-list");
  });
  jqXHR.fail(function(jqxhr, textStatus, error) {
    var err;
    err = textStatus + ", " + error;
    console.log("Request Failed: " + err);
  });
  jqXHR.always(function() {
    console.log("always");
  });
};

selectScript = function(scriptIdx) {
  console.log("script = " + scriptIdx);
  return console.log("code = " + window.spideyScripts.scripts[scriptIdx].code);
};
